name: rebuild-purr-balancer

on:
  push:
    branches: ['main']
    paths: ['PurrBalancer/**']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.69.180.67
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Update and install .NET 8.0
            apt-get update
            apt-get install -y dotnet-sdk-8.0
            
            # Configure Git
            git config --global user.name "GitHub Actions"
            git config --global credential.helper store
            echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > ~/.git-credentials
            
            # Clone the repository only if it doesn't exist
            [ -d PurrLay ] || git clone https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} PurrLay
            cd PurrLay
            
            # Reset and clean repository
            git reset --hard @{u}
            git clean -df
            git pull
            
            # Stop existing service and build the project
            sudo killall -9 PurrBalancer || true
            cd PurrBalancer
            dotnet build --property:Configuration=Release
            
            # Start the service
            sudo nohup ./bin/Release/net8.0/PurrBalancer > /dev/null 2>&1 &
            exit
