name: Deploy PurrEU1

on:
  push:
    branches: ['main']
    paths: ['PurrLay/**']
  workflow_dispatch:

jobs:
  deploy-purrlay:
    uses: ./.github/workflows/deployer.yml
    with:
      host_ip: "159.69.180.67"
      service_name: "PurrLay"
      domain: "eu1.purrlay.riten.dev"
      repo_dir: "PurrRelayer"
      cert_password: "AnotherSecurePasswordHerePurrLay0"
